/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rolldicerandomizer;

import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Teano
 */
public class DiceRandomizerInterface extends javax.swing.JFrame {

    /**
     * Creates new form DiceRandomizerInterface
     */
    public DiceRandomizerInterface() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rollBTN = new javax.swing.JButton();
        Dice2 = new javax.swing.JLabel();
        Dice1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        rollBTN.setBackground(new java.awt.Color(255, 255, 255));
        rollBTN.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        rollBTN.setForeground(new java.awt.Color(255, 0, 0));
        rollBTN.setText("ROLL");
        rollBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollBTNActionPerformed(evt);
            }
        });

        Dice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rolldicerandomizer/6.png"))); // NOI18N

        Dice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rolldicerandomizer/4.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Score :");

        score.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        score.setForeground(new java.awt.Color(102, 255, 0));
        score.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rollBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Dice1)
                        .addGap(124, 124, 124)
                        .addComponent(Dice2)
                        .addGap(165, 165, 165))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(score)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(rollBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dice1)
                    .addComponent(Dice2))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(score))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public static int totalscore;
    private void rollBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollBTNActionPerformed

        Random ran = new Random();
        Border whiteline = BorderFactory.createLineBorder(Color.white,5);
        Border redline = BorderFactory.createLineBorder(Color.red,5);
        Border greenline = BorderFactory.createLineBorder(Color.green,5);
        
        Dice1.setBorder(whiteline);
        Dice2.setBorder(whiteline);

         

        Thread tr1 = new Thread() {
            @Override
            public void run() {
                
                try {
                    int index1 = 0;
                    int index2 = 0;
                    
                    for (int i = 0; i < 5; i++) {
                        Thread.sleep(150);
                        
                        index1 = ran.nextInt(6);
                        index2  = ran.nextInt(6);
                        
                        
                          
                        String[] images = {"/rolldicerandomizer/1.png", "/rolldicerandomizer/2.png", "/rolldicerandomizer/3.png", "/rolldicerandomizer/4.png", "/rolldicerandomizer/5.png", "/rolldicerandomizer/6.png"};
                      
                        
                        Dice1.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[index1])));
                         Dice2.setIcon(new javax.swing.ImageIcon(getClass().getResource(images[index2])));
     
                    }
          
                    
                    System.out.println(index1 + ", " + index2);
                    if(index1 == index2){
                       totalscore = totalscore + 1;
                       Dice1.setBorder(greenline);
                        Dice2.setBorder(greenline);
                        System.out.println("Dice Mathced");
                    }
                    else{
                        totalscore = totalscore;
                         Dice1.setBorder(redline);
                          Dice2.setBorder(redline);
                           System.out.println("Dice Didnt Mathced");
                    }
                    
                    score.setText(String.valueOf(totalscore));
                   
                    
                    
                    
                    
                    
                    
                    

                } catch (Exception e) {
                    System.out.println("error at " + e);
                }

            }
        };
        tr1.start();
        
        
        

    }//GEN-LAST:event_rollBTNActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceRandomizerInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceRandomizerInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceRandomizerInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceRandomizerInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceRandomizerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dice1;
    private javax.swing.JLabel Dice2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rollBTN;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
