/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acitivity5;

import java.util.Date;

/**
 *
 * @author Teano
 */
public class LoanCalculator extends javax.swing.JFrame {

    /**
     * Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yearInterest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numberYears = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loanAmount = new javax.swing.JTextField();
        computeBTN = new javax.swing.JButton();
        dateDisplay = new javax.swing.JLabel();
        monthlyDisplay = new javax.swing.JLabel();
        totalDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" Enter Yearly Interest Rate i.e 8.25 ");

        jLabel2.setText("Enter Number of Years as an Integer");

        jLabel3.setText("Enter Loan Amount (i.e 120000.95)");

        computeBTN.setText("Compute My Loan");
        computeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBTNActionPerformed(evt);
            }
        });

        dateDisplay.setText("Date Displays Here.");

        monthlyDisplay.setText("Monthly Payment Displays Here.");

        totalDisplay.setText("Total Payment Displays Here.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(numberYears, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(yearInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(computeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(monthlyDisplay)
                            .addComponent(dateDisplay)
                            .addComponent(totalDisplay))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(yearInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberYears, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(computeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(dateDisplay)
                .addGap(18, 18, 18)
                .addComponent(monthlyDisplay)
                .addGap(18, 18, 18)
                .addComponent(totalDisplay)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    private void computeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBTNActionPerformed
      Loan loancalculator = new Loan();
      
        
        String YearInterest =  yearInterest.getText().toString();
        String NumYears =  numberYears.getText().toString();
        String Amount =  loanAmount.getText().toString();
        
        double InterestRate = Double.parseDouble(YearInterest);
        int Years = Integer.parseInt(NumYears);
        double Loan = Double.parseDouble(Amount);
        
        loancalculator.setAnnualInterestRate(InterestRate);
        loancalculator.setNumberOfYears(Years);
        loancalculator.setLoanAmount(Loan);
        
        
        
        
        dateDisplay.setText("The loan was created on " + String.valueOf(loancalculator.getLoanDate()));
        monthlyDisplay.setText("The monthly Payment is " + String.valueOf(loancalculator.getMonthlyPayment()));
        totalDisplay.setText("The total payment is " + String.valueOf(loancalculator.getTotalPayment()));
        
    
            System.out.println(loancalculator.getAnnualInterestRate());
            System.out.println(loancalculator.getNumberOfYears());
            System.out.println(loancalculator.getLoanAmount());
          
          
            System.out.println(loancalculator.getMonthlyPayment());
            System.out.println(loancalculator.getTotalPayment());
      
              
        
        
                    
    }//GEN-LAST:event_computeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computeBTN;
    private javax.swing.JLabel dateDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField loanAmount;
    private javax.swing.JLabel monthlyDisplay;
    private javax.swing.JTextField numberYears;
    private javax.swing.JLabel totalDisplay;
    private javax.swing.JTextField yearInterest;
    // End of variables declaration//GEN-END:variables
}
